version: '3'
services:
    app:
      container_name: "task_api"
      build:
        context: .
        dockerfile: docker/app.dockerfile
      volumes:
        - '.:/var/www'
      networks:
        - app_network
      depends_on:
        - mysql
        - redis

    nginx:
      container_name: "task_server"
      restart: unless-stopped
      build:
        context: .
        dockerfile: docker/nginx.dockerfile
      ports:
        - "8084:80"
      volumes:
        - ./public:/var/www/public
        - ./storage/app/public:/var/www/public/storage
      networks:
        - app_network
      depends_on:
        - app

    mysql:
      container_name: "task_database"
      image: 'mysql:8'
      ports:
        - '3309:3306'
      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - 'mysql_data:/var/lib/mysql'
      networks:
        - app_network

    redis:
      container_name: "task_redis"
      image: 'redis:6.2-alpine'
      ports:
        - '6379:6379'
      volumes:
        - 'redis_data:/data'
      networks:
        - app_network


networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
